name: 'lambda-rust-cargo-action'
description: 'Build rust lambdas'
inputs:
  args:  # id of input
    description: 'args to pass to cargo'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
